package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"
)

type Variables struct {
	BinaryName     string
	DockerRegistry string
}

var model = `
GOCMD=go
GOTEST=$(GOCMD) test
GOVET=$(GOCMD) vet
BINARY_NAME={{.BinaryName}}
VERSION?=0.0.0
DOCKER_REGISTRY?={{.DockerRegistry}}

GREEN  := $(shell tput -Txterm setaf 2)
YELLOW := $(shell tput -Txterm setaf 3)
WHITE  := $(shell tput -Txterm setaf 7)
RESET  := $(shell tput -Txterm sgr0)

.PHONY: all build clean

all: help

## Build:
build: ## Build the Go project
	mkdir -p out/bin
	GO111MODULE=on $(GOCMD) build -o out/bin/$(BINARY_NAME) .

clean: ## Clean all the files and binaries generated by the Makefile
	rm -rf ./out

## Test:
test: ## Run the tests of the project
ifeq ($(EXPORT_RESULT), true)
	GO111MODULE=off go get -u github.com/jstemmer/go-junit-report
	$(eval OUTPUT_OPTIONS = | tee /dev/tty | go-junit-report -set-exit-code > junit-report.xml)
endif
	$(GOTEST) -v -race ./... $(OUTPUT_OPTIONS)

coverage: ## Run the tests of the project and export the coverage
	$(GOTEST) -cover -covermode=count -coverprofile=profile.cov ./...
	$(GOCMD) tool cover -func profile.cov
ifeq ($(EXPORT_RESULT), true)
	GO111MODULE=off go get -u github.com/AlekSi/gocov-xml
	GO111MODULE=off go get -u github.com/axw/gocov/gocov
	gocov convert profile.cov | gocov-xml > coverage.xml
endif

## Docker:
docker-build: ## Use the Dockerfile to build the container
	docker build --rm --tag $(BINARY_NAME) .

docker-release: ## Release the container with tag latest and version
	docker tag $(BINARY_NAME) $(DOCKER_REGISTRY)/$(BINARY_NAME):latest
	docker tag $(BINARY_NAME) $(DOCKER_REGISTRY)/$(BINARY_NAME):$(VERSION)

	docker push $(DOCKER_REGISTRY)/$(BINARY_NAME):latest
	docker push $(DOCKER_REGISTRY)/$(BINARY_NAME):$(VERSION)

## Help:
help: ## Show this help
	@echo ''
	@echo 'Usage:'
	@echo '  ${YELLOW}make${RESET} ${GREEN}<target>${RESET}'
	@echo ''
	@echo 'Targets:'
	@awk 'BEGIN {FS = ":.*?## "} { \
		if (/^[a-zA-Z_-]+:.*?##.*$$/) {printf "    ${YELLOW}%-20s${GREEN}%s${RESET}\n", $$1, $$2} \
		else if (/^## .*$$/) {printf "  ${CYAN}%s${RESET}\n", substr($$1,4)} \
		}' $(MAKEFILE_LIST)

`

func main() {
	if len(os.Args) != 2 {
		fmt.Printf("No path provided.\nUsage: %s <path>\n", os.Args[0])
		os.Exit(1)
	}
	var v Variables

	reader := bufio.NewReader(os.Stdin)
	v.askForVariables(reader)

	f, err := os.Create(os.Args[1] + "/Makefile")
	if err != nil {
		log.Println("create file: ", err)
		return
	}
	defer f.Close()

	t, err := template.New("Makefile").Parse(model)
	if err != nil {
		log.Print(err)
		return
	}

	err = t.Execute(f, v)
	if err != nil {
		log.Print("execute: ", err)
		return
	}
}

func (v *Variables) askForVariables(r *bufio.Reader) error {
	fmt.Printf("What is the binary name? ")
	text, err := r.ReadString('\n')
	if err != nil {
		return err
	}
	v.BinaryName = strings.Replace(text, "\n", "", -1)

	fmt.Printf("What is the Docker registry? ")
	text, err = r.ReadString('\n')
	if err != nil {
		return err
	}
	v.DockerRegistry = strings.Replace(text, "\n", "", -1)

	return nil
}
